baseURL = "http://support.jiffyrpa.com.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "Welcome to the Jiffy-RPA Help Center"
theme ="docube"

[params]
  menu = [ "1. Getting Started With Jiffy", "2. Task Design - Task Plan", "3. Task Design - Configurations", "4. Task Design - Tasks", "5. Task Design - Tasks - Objects And Properties", "6. Mappings", "7. UI Tasks", "8. Components", "9. Task Execution", "10. Repository", "11. Settings" ]
